---
ID: "cca8fd99-df35-41c3-b28a-bdab8223b96b"
Parent: "f5e9889b-b746-47ec-a0e5-2c771c0c7c5e"
Template: "f5e9889b-b746-47ec-a0e5-2c771c0c7c5e"
Path: "/sitecore/templates/Project/sv-commerce/Page Design Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {F5E9889B-B746-47EC-A0E5-2C771C0C7C5E}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "29a935b8-beb2-42b0-a8d9-80f38dc56451"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250528T105637Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tilak.sheta@sourceved.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tilak.sheta@sourceved.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dc8a50a2-fc6e-4fc8-9e10-23fc20002558"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tilak.sheta@sourceved.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250528T105639Z
