---
ID: "560ad72d-b20f-4d31-8b30-948ea204ae2d"
Parent: "195954f2-8a15-4ebd-89e0-429baa896ca9"
Template: "195954f2-8a15-4ebd-89e0-429baa896ca9"
Path: /sitecore/templates/Project/svstore/Page Design Folder/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
