---
ID: "59531a4f-c932-5a03-bbe5-83b010fc0c24"
Parent: "5872b437-8a42-5001-ab8e-3f8b196b255f"
Template: "5872b437-8a42-5001-ab8e-3f8b196b255f"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-FieldUsage-ItemLink Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
