---
ID: "d8ab587a-0f46-5961-984d-cb69cd7f935f"
Parent: "bfca8030-6380-5a36-8618-be1d02fa6a6a"
Template: "bfca8030-6380-5a36-8618-be1d02fa6a6a"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-FieldUsage-Text Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
