---
ID: "fd3a64c9-fd52-4211-9768-05780b07e3b3"
Parent: "a8376828-2ea4-419c-9024-8b4e288c931d"
Template: "fcd1a0e3-caec-4f64-8cb2-284a8f63a75a"
Path: "/sitecore/content/sitecore-jss-app/Content/Business Settings/Nop Store Settings"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250416T094517Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b9ac561a-4960-43b8-8430-1bb9cafac6af"
    - ID: "9a5cf0c1-5354-4ad1-8770-79fa5738beee"
      Hint: API_KEY
      Value: 2cJNduxMpkrhSyRyZaoV9pS6GjIt2Ll/166WhOXCdh0=
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d1be68eb-3197-45cd-b1c8-422311651f43"
      Hint: COMMERCE_BASE_URL
      Value: "https://sv103devtestingsc.dev.local/nopstore/api"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250427T113541Z
