---
ID: "186a3175-b991-45fe-ae7f-7764debc1925"
Parent: "c9309ce8-0cb2-4c6e-a228-84a0f2238808"
Template: "fcd1a0e3-caec-4f64-8cb2-284a8f63a75a"
Path: "/sitecore/content/sv-commerce/sv-commerce/Content/Business Settings/Nop Store Settings"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250416T094517Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "66f05610-a51e-4733-8f03-bf0591197b44"
    - ID: "9a5cf0c1-5354-4ad1-8770-79fa5738beee"
      Hint: API_KEY
      Value: MZOmMTyi7KP6sPCcn5hSlRpFYbBEvKB2+I40GFCtwso=
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tilak.sheta@sourceved.com
    - ID: "d1be68eb-3197-45cd-b1c8-422311651f43"
      Hint: COMMERCE_BASE_URL
      Value: "https://localhost:5001/api"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250528T130048Z
