---
ID: "34abc4ee-62a8-5a35-9c17-86ecb7f07229"
Parent: "2ad92baf-0e5c-5eeb-8461-d365c4dca9a0"
Template: "2ad92baf-0e5c-5eeb-8461-d365c4dca9a0"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-FieldUsage-Link Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
