---
ID: "71e746d7-1c1c-500a-bfda-e08a1523b0e5"
Parent: "6dde97a7-79f5-5228-b771-98733965ca16"
Template: "6dde97a7-79f5-5228-b771-98733965ca16"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-FieldUsage-Checkbox Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
