---
ID: "079e45af-e463-51a7-a8c0-cdd301fc9588"
Parent: "5d97de94-bd48-55c3-8559-1747ee04362f"
Template: "5d97de94-bd48-55c3-8559-1747ee04362f"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-Layout-Tabs-Tab Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
