---
ID: "becb9e30-d283-527e-9e6c-924a22ff2b54"
Parent: "ae432642-59d5-5e86-973a-3b4c701bdfea"
Template: "ae432642-59d5-5e86-973a-3b4c701bdfea"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-Layout-Reuse Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
