---
ID: "56d87566-0ea4-5a85-8192-c3731bcebaeb"
Parent: "231a9ae4-5a2d-5d75-a85b-cdaef0731b77"
Template: "231a9ae4-5a2d-5d75-a85b-cdaef0731b77"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-FieldUsage-RichText Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
