---
ID: "36b873c6-312e-5ff8-8bf1-44315954e578"
Parent: "df901d49-1376-5c47-affd-ae9d2ac6c8be"
Template: "df901d49-1376-5c47-affd-ae9d2ac6c8be"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-FieldUsage-ContentList Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
