---
ID: "8a710d3e-080c-53ce-88c8-281ca646f282"
Parent: "41a9cd93-433c-58f3-b5ac-24e6f465dd70"
Template: "41a9cd93-433c-58f3-b5ac-24e6f465dd70"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-RouteFields Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
