---
ID: "06f3b5d8-f45d-5fc5-9d51-036d8db0f263"
Parent: "7d7ca834-af9b-5932-884f-a141bab8d1fc"
Template: "7d7ca834-af9b-5932-884f-a141bab8d1fc"
Path: "/sitecore/templates/Project/sitecore-jss-app/GraphQL-IntegratedDemo Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
