---
ID: "596e36b9-e657-59c7-9de9-9138ed9dc58e"
Parent: "ef1e8d79-e390-58e8-8277-ad743a882f31"
Template: "ef1e8d79-e390-58e8-8277-ad743a882f31"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-CustomRouteType Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250528T105136Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9e7db4c0-e8fb-49fd-973e-966e0aec1363"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tilak.sheta@sourceved.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250528T105136Z
