---
ID: "596e36b9-e657-59c7-9de9-9138ed9dc58e"
Parent: "ef1e8d79-e390-58e8-8277-ad743a882f31"
Template: "ef1e8d79-e390-58e8-8277-ad743a882f31"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-CustomRouteType Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
