---
ID: "4afdc143-cfd7-4e86-b57b-e31184d9d12e"
Parent: "34de528b-8eb0-4564-9895-901e5007f61d"
Template: "34de528b-8eb0-4564-9895-901e5007f61d"
Path: /sitecore/templates/Project/svstore/Headless Site/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
