---
ID: "e45ef65c-299f-4833-a3fd-8fc73b7c2c39"
Parent: "91aa6164-553b-4315-b689-ea1bcd34d47b"
Template: "91aa6164-553b-4315-b689-ea1bcd34d47b"
Path: /sitecore/templates/Project/svstore/Partial Designs/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
