---
ID: "75b157bd-6f85-55d6-acb8-6996e1fcfb58"
Parent: "f4cc2773-1220-5580-a0e3-ac87d4e9131d"
Template: "f4cc2773-1220-5580-a0e3-ac87d4e9131d"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-FieldUsage-Date Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
