---
ID: "aa2a4c40-4a4a-5991-8e88-0b38add68bc8"
Parent: "3ae40bf6-24e7-5b69-a4dd-65bfc33fc1cd"
Template: "3ae40bf6-24e7-5b69-a4dd-65bfc33fc1cd"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-FieldUsage-Number Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
