---
ID: "63df64fb-4b8b-5872-8bf8-11eddeb44bbc"
Parent: "86578000-f41b-5a54-b7bb-736668cf58e0"
Template: "86578000-f41b-5a54-b7bb-736668cf58e0"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-SitecoreContext Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
