---
ID: "0271ae4b-9009-4115-abd3-cc403a283d1e"
Parent: "3a694d3f-5b6a-4d44-ab30-84a82e4a35b8"
Template: "3a694d3f-5b6a-4d44-ab30-84a82e4a35b8"
Path: /sitecore/templates/Project/svstore/Partial Design Folder/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
