---
ID: "bc4c5a04-e078-5e52-8240-37575289d243"
Parent: "d486b781-9b4a-52f6-8e0e-764505cec1f3"
Template: "d486b781-9b4a-52f6-8e0e-764505cec1f3"
Path: "/sitecore/templates/Project/sitecore-jss-app/GraphQL-ConnectedDemo Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
