---
ID: "ea4861d9-c808-54f7-965a-d6f29b6cc273"
Parent: "c5a4e9f9-b7f5-58a5-84ff-1e0cc7fb9a97"
Template: "c5a4e9f9-b7f5-58a5-84ff-1e0cc7fb9a97"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-Section Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
