---
ID: "76e59efa-7aff-500b-a751-894bc1d611e8"
Parent: "e754c168-7f83-526e-ae5c-d95933513720"
Template: "e754c168-7f83-526e-ae5c-d95933513720"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-Layout-Tabs Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
