---
ID: "c6c9b625-29f5-5f29-ba32-75c2ef7c5555"
Parent: "5c05c5c7-dd8a-5bc7-8b72-7382e792c9ce"
Template: "5c05c5c7-dd8a-5bc7-8b72-7382e792c9ce"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-ComponentParams Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
