---
ID: "c27ced87-df63-5e29-a05c-70b9d74f9de7"
Parent: "11d2d1fd-05c7-5209-aa04-cda476b5cbcb"
Template: "11d2d1fd-05c7-5209-aa04-cda476b5cbcb"
Path: "/sitecore/templates/Project/sitecore-jss-app/Styleguide-Layout Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
