---
ID: "1196bea2-5691-5a13-93a4-2ec4813f7ed7"
Parent: "c4888e51-480c-5c94-b5b6-fc5022995281"
Template: "c4888e51-480c-5c94-b5b6-fc5022995281"
Path: "/sitecore/templates/Project/sitecore-jss-app/ContentBlock Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
